/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BhvrRouteImport } from './routes/bhvr'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as DashboardVideosIndexRouteImport } from './routes/dashboard/videos/index'
import { Route as CreateVideoIndexRouteImport } from './routes/create/video/index'
import { Route as DashboardVideosVideoIDRouteImport } from './routes/dashboard/videos/$videoID'
import { Route as CreateVideoVideoIDRouteImport } from './routes/create/video/$videoID'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BhvrRoute = BhvrRouteImport.update({
  id: '/bhvr',
  path: '/bhvr',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVideosIndexRoute = DashboardVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CreateVideoIndexRoute = CreateVideoIndexRouteImport.update({
  id: '/create/video/',
  path: '/create/video/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVideosVideoIDRoute = DashboardVideosVideoIDRouteImport.update({
  id: '/videos/$videoID',
  path: '/videos/$videoID',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CreateVideoVideoIDRoute = CreateVideoVideoIDRouteImport.update({
  id: '/create/video/$videoID',
  path: '/create/video/$videoID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bhvr': typeof BhvrRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/create': typeof CreateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/create/video/$videoID': typeof CreateVideoVideoIDRoute
  '/dashboard/videos/$videoID': typeof DashboardVideosVideoIDRoute
  '/create/video': typeof CreateVideoIndexRoute
  '/dashboard/videos': typeof DashboardVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bhvr': typeof BhvrRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/create': typeof CreateIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/create/video/$videoID': typeof CreateVideoVideoIDRoute
  '/dashboard/videos/$videoID': typeof DashboardVideosVideoIDRoute
  '/create/video': typeof CreateVideoIndexRoute
  '/dashboard/videos': typeof DashboardVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bhvr': typeof BhvrRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/create/': typeof CreateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/create/video/$videoID': typeof CreateVideoVideoIDRoute
  '/dashboard/videos/$videoID': typeof DashboardVideosVideoIDRoute
  '/create/video/': typeof CreateVideoIndexRoute
  '/dashboard/videos/': typeof DashboardVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bhvr'
    | '/login'
    | '/signup'
    | '/create'
    | '/dashboard/'
    | '/create/video/$videoID'
    | '/dashboard/videos/$videoID'
    | '/create/video'
    | '/dashboard/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bhvr'
    | '/login'
    | '/signup'
    | '/create'
    | '/dashboard'
    | '/create/video/$videoID'
    | '/dashboard/videos/$videoID'
    | '/create/video'
    | '/dashboard/videos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bhvr'
    | '/login'
    | '/signup'
    | '/create/'
    | '/dashboard/'
    | '/create/video/$videoID'
    | '/dashboard/videos/$videoID'
    | '/create/video/'
    | '/dashboard/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BhvrRoute: typeof BhvrRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CreateIndexRoute: typeof CreateIndexRoute
  CreateVideoVideoIDRoute: typeof CreateVideoVideoIDRoute
  CreateVideoIndexRoute: typeof CreateVideoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bhvr': {
      id: '/bhvr'
      path: '/bhvr'
      fullPath: '/bhvr'
      preLoaderRoute: typeof BhvrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/videos/': {
      id: '/dashboard/videos/'
      path: '/videos'
      fullPath: '/dashboard/videos'
      preLoaderRoute: typeof DashboardVideosIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/create/video/': {
      id: '/create/video/'
      path: '/create/video'
      fullPath: '/create/video'
      preLoaderRoute: typeof CreateVideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/videos/$videoID': {
      id: '/dashboard/videos/$videoID'
      path: '/videos/$videoID'
      fullPath: '/dashboard/videos/$videoID'
      preLoaderRoute: typeof DashboardVideosVideoIDRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/create/video/$videoID': {
      id: '/create/video/$videoID'
      path: '/create/video/$videoID'
      fullPath: '/create/video/$videoID'
      preLoaderRoute: typeof CreateVideoVideoIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BhvrRoute: BhvrRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CreateIndexRoute: CreateIndexRoute,
  CreateVideoVideoIDRoute: CreateVideoVideoIDRoute,
  CreateVideoIndexRoute: CreateVideoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
